import { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { getTrips } from '@/lib/trips';
import { IRS_BUSINESS_RATE, IRS_YEAR, CURRENCY_FORMAT, MILES_FORMAT } from '@/config/irs-rate';
import type { Trip, TripCategory } from '@/types';
import jsPDF from 'jspdf';

export function Reports() {
  const { user } = useAuth();
  const [startDate, setStartDate] = useState(`${new Date().getFullYear()}-01-01`);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [trips, setTrips] = useState<Trip[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const fetchTrips = async () => {
    if (!user) return;
    setLoading(true); setError('');
    try {
      const data = await getTrips(user.id, {
        startDate: `${startDate}T00:00:00`,
        endDate: `${endDate}T23:59:59`,
        limit: 1000,
      });
      setTrips(data);
    } catch (e: any) { setError(e.message); }
    setLoading(false);
  };

  const businessTrips = trips.filter(t => t.category === 'business');
  const totalBusinessMiles = businessTrips.reduce((sum, t) => sum + t.distance_miles, 0);
  const totalDeduction = totalBusinessMiles * IRS_BUSINESS_RATE;

  // Group by category
  const byCategory = (['business', 'personal', 'medical', 'charity'] as TripCategory[]).reduce((acc, cat) => {
    const catTrips = trips.filter(t => t.category === cat);
    acc[cat] = { trips: catTrips, miles: catTrips.reduce((s, t) => s + t.distance_miles, 0) };
    return acc;
  }, {} as Record<TripCategory, { trips: Trip[]; miles: number }>);

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.text('MilesWorth', 20, 20);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('IRS Mileage Report', 20, 28);

    // Report info
    doc.setTextColor(0);
    doc.setFontSize(11);
    doc.text(`Report Period: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`, 20, 42);
    doc.text(`IRS ${IRS_YEAR} Standard Business Rate: ${CURRENCY_FORMAT.format(IRS_BUSINESS_RATE)}/mile`, 20, 50);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 58);

    // Separator
    doc.setDrawColor(200);
    doc.line(20, 64, pageWidth - 20, 64);

    // Summary by category
    let y = 74;
    doc.setFontSize(14);
    doc.text('Summary by Category', 20, y);
    y += 10;

    doc.setFontSize(11);
    for (const [cat, data] of Object.entries(byCategory)) {
      if (data.trips.length === 0) continue;
      const deduction = cat === 'business' ? data.miles * IRS_BUSINESS_RATE : 0;
      doc.text(`${cat.charAt(0).toUpperCase() + cat.slice(1)}:`, 20, y);
      doc.text(`${MILES_FORMAT.format(data.miles)} miles`, 80, y);
      doc.text(`${data.trips.length} trips`, 120, y);
      if (cat === 'business') {
        doc.text(`Deduction: ${CURRENCY_FORMAT.format(deduction)}`, 150, y);
      }
      y += 8;
    }

    // Totals
    y += 4;
    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);
    y += 10;
    doc.setFontSize(12);
    doc.text(`Total Business Miles: ${MILES_FORMAT.format(totalBusinessMiles)}`, 20, y);
    y += 8;
    doc.text(`Estimated Business Deduction: ${CURRENCY_FORMAT.format(totalDeduction)}`, 20, y);
    y += 8;
    doc.text(`Total Trips: ${trips.length}`, 20, y);

    // Trip details
    if (businessTrips.length > 0) {
      y += 16;
      doc.setFontSize(14);
      doc.text('Business Trip Details', 20, y);
      y += 10;

      doc.setFontSize(9);
      doc.text('Date', 20, y);
      doc.text('Miles', 55, y);
      doc.text('Vehicle', 80, y);
      doc.text('Purpose', 120, y);
      y += 6;

      for (const trip of businessTrips) {
        if (y > 270) { doc.addPage(); y = 20; }
        const date = new Date(trip.started_at).toLocaleDateString();
        doc.text(date, 20, y);
        doc.text(MILES_FORMAT.format(trip.distance_miles), 55, y);
        doc.text(trip.vehicle?.name || '-', 80, y);
        doc.text(trip.purpose || '-', 120, y);
        y += 6;
      }
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text(
        'This report is generated by MilesWorth for informational purposes. Consult a tax professional for advice.',
        pageWidth / 2, 290, { align: 'center' }
      );
    }

    doc.save(`milesworth-report-${startDate}-to-${endDate}.pdf`);
  };

  const exportCSV = () => {
    if (businessTrips.length === 0) return;
    
    // Group by month
    const byMonth: Record<string, { miles: number; deduction: number; count: number }> = {};
    for (const trip of businessTrips) {
      const month = trip.started_at.slice(0, 7);
      if (!byMonth[month]) byMonth[month] = { miles: 0, deduction: 0, count: 0 };
      byMonth[month].miles += trip.distance_miles;
      byMonth[month].deduction += trip.distance_miles * IRS_BUSINESS_RATE;
      byMonth[month].count++;
    }

    const rows = [
      ['Month', 'Business Miles', 'Trips', 'Estimated Deduction'],
      ...Object.entries(byMonth).sort().map(([month, data]) => [
        month,
        data.miles.toFixed(1),
        data.count.toString(),
        data.deduction.toFixed(2),
      ]),
      ['TOTAL', totalBusinessMiles.toFixed(1), businessTrips.length.toString(), totalDeduction.toFixed(2)],
    ];

    const csv = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `milesworth-quarterly-${startDate}-to-${endDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">Reports</h1>

      {/* Date range picker */}
      <div className="bg-dark-800 rounded-xl p-4 border border-dark-700 space-y-3">
        <h2 className="text-sm font-semibold text-gray-300">Date Range</h2>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block text-xs text-gray-400 mb-1">From</label>
            <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)}
              className="w-full bg-dark-700 border border-dark-600 rounded-lg px-3 py-2 text-sm text-gray-100" />
          </div>
          <div>
            <label className="block text-xs text-gray-400 mb-1">To</label>
            <input type="date" value={endDate} onChange={e => setEndDate(e.target.value)}
              className="w-full bg-dark-700 border border-dark-600 rounded-lg px-3 py-2 text-sm text-gray-100" />
          </div>
        </div>
        <button onClick={fetchTrips} disabled={loading}
          className="w-full bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white font-medium py-2 rounded-lg transition-colors">
          {loading ? 'Loading...' : 'Load trips'}
        </button>
      </div>

      {error && <div className="bg-red-500/10 border border-red-500/30 text-red-400 text-sm rounded-lg p-3">{error}</div>}

      {/* Results */}
      {trips.length > 0 && (
        <>
          <div className="bg-dark-800 rounded-xl p-4 border border-dark-700">
            <h2 className="text-sm font-semibold text-gray-300 mb-3">Summary</h2>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs text-gray-400">Business Miles</p>
                <p className="text-xl font-bold text-brand-400">{MILES_FORMAT.format(totalBusinessMiles)}</p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Est. Deduction</p>
                <p className="text-xl font-bold text-green-400">{CURRENCY_FORMAT.format(totalDeduction)}</p>
              </div>
            </div>
          </div>

          <div className="flex gap-3">
            <button onClick={generatePDF}
              className="flex-1 bg-brand-600 hover:bg-brand-700 text-white font-medium py-3 rounded-lg transition-colors">
              IRS PDF Report
            </button>
            <button onClick={exportCSV}
              className="flex-1 bg-dark-700 hover:bg-dark-600 border border-dark-600 text-gray-200 font-medium py-3 rounded-lg transition-colors">
              Quarterly CSV
            </button>
          </div>
        </>
      )}

      {trips.length === 0 && !loading && (
        <div className="bg-dark-800 rounded-xl p-8 border border-dark-700 text-center">
          <p className="text-gray-400">Select a date range and click "Load trips" to generate reports.</p>
        </div>
      )}
    </div>
  );
}
