import { Link } from 'react-router-dom';

export function Terms() {
  return (
    <div className="min-h-screen">
      <nav className="border-b border-dark-700">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/" className="text-lg font-bold text-brand-500">MilesWorth</Link>
          <Link to="/" className="text-sm text-gray-400 hover:text-gray-200">Back to home</Link>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-4 py-12 prose prose-invert prose-sm">
        <h1>Terms of Service</h1>
        <p className="text-gray-400">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <h2>What MilesWorth is</h2>
        <p>MilesWorth is a mileage tracking tool for self-employed workers. It helps you log business drives and generate reports for tax purposes. It is not tax advice.</p>

        <h2>What MilesWorth is not</h2>
        <ul>
          <li>MilesWorth is not a tax preparation service.</li>
          <li>MilesWorth does not file taxes on your behalf.</li>
          <li>MilesWorth does not provide legal or financial advice.</li>
          <li>The reports generated by MilesWorth are for your records. Consult a tax professional for tax filing.</li>
        </ul>

        <h2>IRS disclaimer</h2>
        <p>The standard mileage rates used in MilesWorth are based on IRS publications and are updated annually. These rates are provided for informational purposes only. MilesWorth is not affiliated with the IRS. Always consult a qualified tax professional for advice specific to your situation.</p>

        <h2>Accounts</h2>
        <p>You must be at least 18 years old to create an account. You are responsible for maintaining the security of your account credentials. One account per person.</p>

        <h2>Subscriptions</h2>
        <p>Pro plans are billed through Stripe. You can cancel at any time from the billing portal in your Settings. Cancellation takes effect at the end of your current billing period. No partial refunds for unused time.</p>

        <h2>Free tier</h2>
        <p>The free tier allows 5 trips per month with no credit card required. We reserve the right to change free tier limits with 30 days' notice.</p>

        <h2>Data and uptime</h2>
        <p>We strive to keep MilesWorth available and your data safe, but we cannot guarantee 100% uptime. You are responsible for keeping your own backups of important trip data. We are not liable for data loss.</p>

        <h2>Changes to these terms</h2>
        <p>We may update these terms occasionally. Significant changes will be communicated by email. Continued use of MilesWorth after changes constitutes acceptance of the updated terms.</p>

        <h2>Contact</h2>
        <p>Questions about these terms? Email us at support@milesworth.io.</p>
      </div>
    </div>
  );
}
